# Generated by Django 4.1.3 on 2023-01-30 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackersite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=500, null=True)),
                ('aboutme', models.CharField(max_length=500, null=True)),
                ('website', models.CharField(max_length=500, null=True)),
                ('github', models.CharField(max_length=500, null=True)),
                ('twitter', models.CharField(max_length=500, null=True)),
                ('instagram', models.CharField(max_length=500, null=True)),
                ('facebook', models.CharField(max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
