# Generated by Django 4.1.3 on 2023-01-30 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackersite', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
